[workspace.lints.rust]
unsafe_code = "forbid"

[workspace]
resolver = "2"
members = [
    "crates/libs/lib-utils",
    "crates/libs/lib-auth",
    "crates/libs/lib-core",
    "crates/services/web-airlab",
]
