[env]
RUST_LOG="airlab_web=debug,airlab_lib=debug"
SERVICE_TOKEN_DURATION_SEC="36000"
SERVICE_WEB_FOLDER="web-airlab/"
SERVICE_DATA_PATH="data/airlab-data"
SERVICE_PWD_KEY="<pwd-key>"
SERVICE_TOKEN_KEY="<token-key>"
SERVICE_DB_URL="postgres://<user>:<pwd>@<host>/<db>"
SERVICE_EMAIL_FROM_ADDRESS="<from-email-address>"
SERVICE_EMAIL_FROM_NAME="<from-email-name>"
SERVICE_EMAIL_TOKEN="<email-token>"
SERVICE_EMAIL_ADDRESS="<email-service-url>"
SERVICE_LOG_AGGR_URL="<log-aggregator-url>"
SERVICE_RESET_PWD_URL="<reset-password-url>"
SERVICE_HOST_ADDR="<host-url>"
SERVICE_HOST_PORT="<port-port>"
SUPER_USER="admin@example.com"
SUPER_USER_PWD="changeit"
SETUP_DEMO_GROUP=true
