import type { FilterConfig } from '@/modules/json/api';
import { applicationEnum, statusEnum, conjugateStatusEnum, lotStatusEnum, antigenRetrievalTypes } from '@/utils/enums';

export const globalFilterConfig: FilterConfig[] = [
  {
    key: 'proteinName',
    label: 'Protein Name',
    table: 'Protein',
    field: 'name',
    op: 'contains',
    type: 'text',
  },
  {
    key: 'cloneName',
    label: 'Clone Name',
    table: 'Clone',
    field: 'name',
    op: 'contains',
    type: 'text',
  },
  {
    key: 'tagName',
    label: 'Tag',
    table: 'Tag',
    field: 'name',
    op: 'contains',
    type: 'text',
  },
  {
    key: 'mass',
    label: 'Mass',
    table: 'Tag',
    field: 'mw',
    op: 'eq',
    type: 'number',
  },
  {
    key: 'conjugateStatus',
    label: 'Conjugate Status',
    table: 'Conjugate',
    field: 'status',
    op: 'eq',
    type: 'select',
    options: conjugateStatusEnum.map(opt => ({ label: opt.text, value: opt.value })),
  },
  {
    key: 'tubeNumber',
    label: 'Tube Number',
    table: 'Conjugate',
    field: 'tube_number',
    op: 'eq',
    type: 'number',
  },
  {
    key: 'speciesName',
    label: 'Species Name',
    table: 'Species',
    field: 'name',
    op: 'contains',
    type: 'text',
  },
  {
    key: 'lotName',
    label: 'Lot Name',
    table: 'Lot',
    field: 'name',
    op: 'contains',
    type: 'text',
  },
  {
    key: 'lotNumber',
    label: 'Lot Number',
    table: 'Lot',
    field: 'number',
    op: 'contains',
    type: 'text',
  },
  {
    key: 'statusName',
    label: 'Status',
    table: 'Lot',
    field: 'status',
    op: 'eq',
    type: 'select',
    options: lotStatusEnum.map(opt => ({ label: opt.text, value: opt.value })),
  },
  {
    key: 'providerName',
    label: 'Provider Name',
    table: 'Provider',
    field: 'name',
    op: 'contains',
    type: 'text',
  },
  {
    key: 'collectionId',
    label: 'Collection',
    table: 'Collection',
    field: 'id',
    op: 'eq',
    type: 'select',
  },
  {
    key: 'validationApplication',
    label: 'Validation Application',
    table: 'Validation',
    field: 'application',
    op: 'eq',
    type: 'select',
    options: applicationEnum.map(opt => ({ label: opt.text, value: opt.value })),
  },
  {
    key: 'panelApplication',
    label: 'Application',
    table: 'Panel',
    field: 'application',
    op: 'eq',
    type: 'select',
    options: applicationEnum.map(opt => ({ label: opt.text, value: opt.value })),
  },
  {
    key: 'panelName',
    label: 'Panel Name',
    table: 'Panel',
    field: 'name',
    op: 'contains',
    type: 'text',
  },
  {
    key: 'validationStatus',
    label: 'Validation Status',
    table: 'Validation',
    field: 'status',
    op: 'eq',
    type: 'select',
    options: statusEnum.map(opt => ({ label: opt.text, value: opt.value })),
  },
  {
    key: 'validationProtocol',
    label: 'Protocol',
    table: 'Validation',
    field: 'antigenRetrievalType',
    op: 'eq',
    type: 'select',
    options: antigenRetrievalTypes.map(value => ({ label: value, value })),
  },
  {
    key: 'reactivity',
    label: 'Reactivity',
    table: 'Clone',
    field: 'reactivity',
    op: 'contains',
    type: 'select',
    multiple: true,
  },
]
